>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

>>> bg = BaseGeometry()
>>> bg = BaseGeometry(None)
Traceback (most recent call last):
...
TypeError: BaseGeometry() takes no arguments

>>> bg.area()
Traceback (most recent call last):
Exception: area() is not implemented

>>> bg.area(1)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 2 were given

>>> bg.area(1, 2)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 3 were given


>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> bg.integer_validator("my_int", 12)

>>> bg.integer_validator("width", 89)

>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
...
ValueError: age must be greater than 0

>>> bg.integer_validator("distance", -4)
Traceback (most recent call last):
...
ValueError: distance must be greater than 0

>>> bg.integer_validator(None)
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator("name")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator("name", None)
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", True)


>>> bg.integer_validator("name", float("inf"))
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", float("-inf"))
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", 1.0)
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", ())
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", {})
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", [])
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", 1, 2)
Traceback (most recent call last):
...
TypeError: integer_validator() takes 3 positional arguments but 4 were given

>>> bg.integer_validator("", 1)

>>> bg.integer_validator(float("inf"), 1)

>>> bg.integer_validator(float("-inf"), 1)

>>> bg.integer_validator((), 1)

>>> bg.integer_validator({}, 1)

>>> bg.integer_validator([], 1)

>>> bg.integer_validator(True, 1)
